#ifndef IMAGES_ARRAYS_H
#define IMAGES_ARRAYS_H

const uint8_t * const player_images[] PROGMEM = { p38_0, p38_1, p38_2, p38_3, p38_4, p38_3, p38_6, p38_1, p38_mask_0, p38_mask_1, p38_2, p38_3, p38_4, p38_3, p38_6, p38_mask_1, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04, p38_shrink_1, p38_shrink_2, p38_shrink_3, p38_shrink_4, p38_shrink_mask_1, p38_shrink_mask_2, p38_shrink_mask_3, p38_shrink_mask_4 };
const uint8_t * const enemy_zero_images[] PROGMEM = { zero_N, zero_NE, zero_E, zero_SE, zero_S, zero_SW, zero_W, zero_NW, zero_mask_N, zero_mask_NE, zero_mask_E, zero_mask_SE, zero_mask_S, zero_mask_SW, zero_mask_W, zero_mask_NW, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_zero_hollow_images[] PROGMEM = { zero_hollow_N, zero_hollow_NE, zero_hollow_E, zero_hollow_SE, zero_hollow_S, zero_hollow_SW, zero_hollow_W, zero_hollow_NW, zero_mask_N, zero_mask_NE, zero_mask_E, zero_mask_SE, zero_mask_S, zero_mask_SW, zero_mask_W, zero_mask_NW, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_medium_images[] PROGMEM = { enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, enemy_medium_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
const uint8_t * const enemy_boat[] PROGMEM = { boat_turrent_N, boat_turrent_NE, boat_turrent_E, boat_turrent_SE, boat_turrent_S, boat_turrent_SW, boat, boat_turrent_NW, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_turrent_mask, boat_mask, boat_turrent_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };
//const uint8_t * const enemy_boat_sinking[] PROGMEM = { boat_sinking_1, boat_sinking_2, boat_sinking_3, boat_sinking_4, boat_sinking_5, boat_sinking_6, boat, boat, boat_sinking_mask_1, boat_sinking_mask_2, boat_sinking_mask_3, boat_sinking_mask_4, boat_sinking_mask_5, boat_sinking_mask_6, boat_mask, boat_mask, explosion_01, explosion_02, explosion_03, explosion_04, explosion_mask_01, explosion_mask_02, explosion_mask_03, explosion_mask_04 };

#endif
